
	<form action="<?= $requestUrl ?>/signup" method="post" class="form">
		<fieldset>
			<legend>Signup</legend>
				<div class="container">

				<div><label>Prénom</label>
				<input type="text" name="firstName"></div>

				<div><label>Nom</label>
				<input type="text" name="lastName"></div>

				<div><label>Email</label>
				<input type="email" name="email"></div>

				<div><label>password</label>
				<input type="password" name="password"></div>

				<div><label>Date de naissance</label>
				<input type="date" name="birthDate"></div>

				<div><label>Adresse</label>
				<input type="text" name="address"></div>

				<div><label>Ville</label>
				<input type="text" name="city"></div>

				<div><label>Code Postal</label>
				<input type="text" name="zipCod"></div>

				<div><label>Pays</label>
				<input type="text" name="country"></div>

				<div><label>Téléphone</label>
				<input type="number" name="phone"></div>

				<div class="button"><button type="submit" >Soumettre</button></div>
				</div>

		</fieldset>
	</form>

